name: CI / CD

on:
  pull_request:
    branches: ["develop", "main"]
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  ci:
    name: ci
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v3.9.1
        with: 
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run typecheck
      - run: npm run build
      
  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Deploy to Cloudtype
        uses: cloudtype-github-actions/deploy@v1
        with:
          token:   ${{ secrets.CLOUDTYPE_TOKEN }}
          project: "@${{ secrets.CLOUDTYPE_SPACE }}/${{ secrets.CLOUDTYPE_APP }}"
          yaml: cloudtype.yml